### ISSUE TITLE
Casos de Testes [1]

### ISSUE THREAD

**Issue by HianySilva** [HianySilva/psvPostoSaudeVirtual#12]

**Comment by FranLari** [comment]
Cadastro de usuário:
 
Scenario 1: Cadastro de usuário
 
Given: 
        	estou na parte de cadastro de usuário 
 
When:
        	Inserir no campo do nome o meu nome e insiro no campo de email o meu email e depois insiro no campo de senha a senha desejada e a mesma senha criada no campo de confirmação de senha
 
Then:
Quando eu clicar no botão cadastrar sou redireciona para página de Login.

**Comment by priscla** [comment]
Cadastro de usuário:

Scenario 1: Cadastro de usuário

Given:
estou na parte de cadastro de usuário

When:
Inserir no campo do nome o meu nome e insiro no campo de email o meu email e depois insiro no campo de senha a senha desejada e a mesma senha criada no campo de confirmação de senha

Then:
Quando eu clicar no botão cadastrar sou redireciona para página de Login.
