### ISSUE TITLE
Prototipagem no Figma [1]

### ISSUE THREAD

**Issue by HianySilva** [HianySilva/psvPostoSaudeVirtual#2]

**Comment by FranLari** [comment]
https://www.figma.com/file/eAXN0zgiN9vTOGDxnhLvOa/Posto-de-Sa%C3%BAde-Virtual?node-id=0%3A1

**Comment by HianySilva** [comment]
https://www.figma.com/proto/eAXN0zgiN9vTOGDxnhLvOa/Posto-de-Sa%C3%BAde-Virtual?node-id=1319%3A11&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1270%3A33
