### ISSUE TITLE
Casos de Teste

### ISSUE THREAD

**Issue by HianySilva** [HianySilva/psvPostoSaudeVirtual#54]

**Comment by HianySilva** [comment]
Consultas:
Scenario 1: Visualizo a tela de  consultas

Given:
eu como usuário visualizo a tela de consultas para ver as consulta disponíveis da semana 
When:
Desejo visualizar a consulta disponível para pode fazer o meu agendamento
Then:
Então depois de ter visualizado a consulta disponível assim consigo prosseguir para a próxima tela

**Comment by FranLari** [comment]
Consultas:
Scenario 1: Visualizo a tela de consultas

Given:
eu como usuário visualizo a tela de consultas para ver as consulta disponíveis da semana
When:
Desejo visualizar a consulta disponível para pode fazer o meu agendamento
Then:
Então depois de ter visualizado a consulta disponível assim consigo prosseguir para a próxima tela
