### ISSUE TITLE
Caso de Testes

### ISSUE THREAD

**Issue by HianySilva** [HianySilva/psvPostoSaudeVirtual#75]

**Comment by HianySilva** [comment]
Minhas consultas:
Scenario 1: Visualizo as minhas consultas

Given:
eu como usuário depois de ter feito o meu agendamento.

When:
Desejo visualizar minhas consultas , e também  alterar se for preciso
Then:
Quando terminar de visualizar ou alterar se for preciso voltarei a tela home.

**Comment by FranLari** [comment]
Minhas consultas:
Scenario 1: Visualizo as minhas consultas

Given:
eu como usuário depois de ter feito o meu agendamento.

When:
Desejo visualizar minhas consultas , e também alterar se for preciso
Then:
Quando terminar de visualizar ou alterar se for preciso voltarei a tela home.
