### ISSUE TITLE
Casos de Testes [2]

### ISSUE THREAD

**Issue by HianySilva** [HianySilva/psvPostoSaudeVirtual#9]

**Comment by FranLari** [comment]
Cadastro de Médico: 

Scenario 1: Cadastro de Médico
Given: 
        	estou na parte de cadastro de médico
 
When:
        	Inserir no campo do nome o meu nome e insiro no campo do CRM o meu CRM, depois coloco no campo de turno o turno que trabalho e no de email o meu email, depois insiro no campo de senha a senha desejada e a mesma senha criada no campo de confirmação de senha
 
Then:
Quando eu clicar no botão cadastrar sou redirecionado para página de Login.
